### ISSUE TITLE
Cannot Enable 2FA

### ISSUE THREAD

**Issue by grizzy255** [dlandon/owncloud#10]
Issue: Cannot Activate TOTP Second-factor Auth
Install TOTP Second-factor Auth from Market 
Goto User > Security and Click on checkbox to Activate TOTP.
Also tried via occ

Seems like its missing the imagick extension. 

Owncloud.log 

{"reqId":"0DycLqQhrmttyLHTG1lb","level":3,"time":"2021-09-27T03:58:13+00:00","remoteAddr":"192.168.1.187","user":"ankush","app":"index","method":"POST","url":"\/index.php\/apps\/twofactor_totp\/settings\/enable","message":"Exception: {\"Exception\":\"BaconQrCode\\\\Exception\\\\RuntimeException\",\"Message\":\"You need to install the imagick extension to use this back end\",\"Code\":0,\"Trace\":\"#0 \\\/config\\\/www\\\/owncloud\\\/apps-external\\\/twofactor_totp\\\/lib\\\/Controller\\\/SettingsController.php(138):

root@0a2af11f76f3:/# uname -a
Linux 0a2af11f76f3 5.13.8-Unraid #1 SMP Wed Aug 4 09:39:46 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux

root@0a2af11f76f3:/# sudo apt install php-imagick
Reading package lists... Done
Building dependency tree       
Reading state information... Done
php-imagick is already the newest version (3.5.1-1+ubuntu20.04.1+deb.sury.org+1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

root@0a2af11f76f3:/# php -m | grep imagick
root@0a2af11f76f3:/# 

root@0a2af11f76f3:/# php -v
PHP 7.4.24 (cli) (built: Sep 23 2021 21:36:11) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.24, Copyright (c), by Zend Technologies

**Comment by dlandon** [comment]
Fixed in latest release.
