### ISSUE TITLE
WebUI doesn't load correctly

### ISSUE THREAD

**Issue by redxon** [dlandon/owncloud#11]
Hello

I have opened an issue with OwnCloud already and was advised to open an issue here as they could not help me. I will relay all information I have shared there (https://central.owncloud.org/t/webui-doesnt-load-correctly/36692) here and am hoping that I don't have to start from scratch as my settings would be lost as I understand it. Now the follwing:

- Steps to reproduce
Updated OwnCloud
Update failed: restored to older version
Restarted Docker Container
WebUI doesn’t load correctly

- Expected behaviour
Owncloud should load correctly and I can access the WebUI

- Actual behaviour
Everything except the WebUI works, but the WebUI shows only this:

[https://central.owncloud.org/uploads/db1708/original/3X/f/3/f30a370627ce2144be20d59c813c5c4726dbefe3.jpeg](url)

I can’t set, view or change anything from there

- Server configuration
Operating system:
  - unRaid 6.9.2 with docker

- Web server:
nginx

- Database:
MariaDB 10.3.34

- PHP version:
7.4

- ownCloud version: (see ownCloud admin page)
10.8.0.4

- Updated from an older ownCloud or fresh install:
Updated from 10.8 to 10.9, update failed, restored to 10.8

I re downloaded everything and imported the backup of my config. So I did this: [Restoring ownCloud :: ownCloud Documentation](https://doc.owncloud.com/server/next/admin_manual/maintenance/backup_and_restore/restore.html)

- Where did you install ownCloud from:
Unraid App Store with this template

- Signing status (ownCloud 9.0 and above):
No errors have been found.

- The content of config/config.php:

`
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis-server.sock",
            "port": 0,
            "timeout": 0
        },
        "instanceid": "oci9p6dbi3d6",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.201",
            "mydomain.tld"
        ],
        "datadirectory": "\/data",
        "overwrite.cli.url": "https:\/\/mydomain.tld\/",
        "overwritehost": "mydomain.tld",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "10.8.0.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "trusted_proxies": [
            "swag"
        ],
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "apps_paths": [
            {
                "path": "\/config\/www\/owncloud\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/config\/www\/owncloud\/apps-external",
                "url": "\/apps-external",
                "writable": true
            }
        ],
        "installed": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "files_external_allow_create_new_local": "true",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "allow_user_to_change_mail_address": ""
    }
}
List of activated apps:

Enabled:
  - comments:
    - Version: 0.3.0
    - Path: /config/www/owncloud/apps/comments
  - configreport:
    - Version: 0.2.0
    - Path: /config/www/owncloud/apps/configreport
  - dav:
    - Version: 0.7.0
    - Path: /config/www/owncloud/apps/dav
  - federatedfilesharing:
    - Version: 0.5.0
    - Path: /config/www/owncloud/apps/federatedfilesharing
  - federation:
    - Version: 0.1.0
    - Path: /config/www/owncloud/apps/federation
  - files:
    - Version: 1.5.2
    - Path: /config/www/owncloud/apps/files
  - files_external:
    - Version: 0.8.0
    - Path: /config/www/owncloud/apps/files_external
  - files_mediaviewer:
    - Version: 1.0.4
    - Path: /config/www/owncloud/apps/files_mediaviewer
  - files_sharing:
    - Version: 0.14.0
    - Path: /config/www/owncloud/apps/files_sharing
  - files_trashbin:
    - Version: 0.9.1
    - Path: /config/www/owncloud/apps/files_trashbin
  - files_versions:
    - Version: 1.3.0
    - Path: /config/www/owncloud/apps/files_versions
  - firstrunwizard:
    - Version: 1.2.0
    - Path: /config/www/owncloud/apps/firstrunwizard
  - gallery:
    - Version: 16.1.1
    - Path: /config/www/owncloud/apps-external/gallery
  - market:
    - Version: 0.6.1
    - Path: /config/www/owncloud/apps/market
  - notifications:
    - Version: 0.5.4
    - Path: /config/www/owncloud/apps/notifications
  - password_policy:
    - Version: 2.1.3
    - Path: /config/www/owncloud/apps-external/password_policy
  - provisioning_api:
    - Version: 0.5.0
    - Path: /config/www/owncloud/apps/provisioning_api
  - systemtags:
    - Version: 0.3.0
    - Path: /config/www/owncloud/apps/systemtags
  - updatenotification:
    - Version: 0.2.1
    - Path: /config/www/owncloud/apps/updatenotification
Disabled:
  - encryption:
    - Path: /config/www/owncloud/apps/encryption
  - external:
    - Path: /config/www/owncloud/apps/external
  - user_external:
    - Path: /config/www/owncloud/apps/user_external
  - windows_network_drive:
    - Path: /config/www/owncloud/apps-external/windows_network_drive

`

- Are you using external storage, if yes which one: local/smb/sftp/…
yes, local

- Are you using encryption: yes/no
no

- Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/…
no

- Client configuration
Browser:
Chrome

- Operating system:
Windows 10

- Logs
Web server error log
2022/03/14 12:20:30 [error] 533#533: *505 open() "/config/www/owncloud/favicon.ico" failed (2: No such file or directory), client: MYIP, server: _, request: "GET /favicon.ico HTTP/1.1", host: "mydomain.tld"

ownCloud log (data/owncloud.log)
`{"reqId":"e3b0fbed-7e36-4d70-b1e9-b338807b88f1","level":3,"time":"2022-03-14T10:08:20+00:00","remoteAddr":"192.168.1.3","user":"--","app":"PHP","method":"GET","url":"\/index.php","message":"include(\/config\/www\/owncloud\/lib\/composer\/composer\/..\/..\/..\/core\/Controller\/SetupController.php): failed to open stream: No such file or directory at \/config\/www\/owncloud\/lib\/composer\/composer\/ClassLoader.php#444"}
{"reqId":"e3b0fbed-7e36-4d70-b1e9-b338807b88f1","level":3,"time":"2022-03-14T10:08:20+00:00","remoteAddr":"192.168.1.3","user":"--","app":"PHP","method":"GET","url":"\/index.php","message":"include(): Failed opening '\/config\/www\/owncloud\/lib\/composer\/composer\/..\/..\/..\/core\/Controller\/SetupController.php' for inclusion (include_path='\/config\/www\/owncloud\/apps') at \/config\/www\/owncloud\/lib\/composer\/composer\/ClassLoader.php#444"}
{"reqId":"e3b0fbed-7e36-4d70-b1e9-b338807b88f1","level":3,"time":"2022-03-14T10:08:20+00:00","remoteAddr":"192.168.1.3","user":"--","app":"index","method":"GET","url":"\/index.php","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OC\\\\Core\\\\Controller\\\\SetupController' not found\",\"Code\":0,\"Trace\":\"#0 \\\/config\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#1 {main}\",\"File\":\"\\\/config\\\/www\\\/owncloud\\\/lib\\\/base.php\",\"Line\":863}"}
{"reqId":"e3b0fbed-7e36-4d70-b1e9-b338807b88f1","level":3,"time":"2022-03-14T10:08:20+00:00","remoteAddr":"192.168.1.3","user":"--","app":"PHP","method":"GET","url":"\/index.php","message":"file_get_contents(\/config\/www\/owncloud\/core\/js\/core.json): failed to open stream: No such file or directory at \/config\/www\/owncloud\/lib\/private\/legacy\/template.php#162"}
{"reqId":"e3b0fbed-7e36-4d70-b1e9-b338807b88f1","level":3,"time":"2022-03-14T10:08:20+00:00","remoteAddr":"192.168.1.3","user":"--","app":"core","method":"GET","url":"\/index.php","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Class 'OC\\\\Core\\\\Controller\\\\SetupController' not found\",\"Code\":0,\"Trace\":\"#0 \\\/config\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#1 {main}\",\"File\":\"\\\/config\\\/www\\\/owncloud\\\/lib\\\/base.php\",\"Line\":863}"}
{"reqId":"e3b0fbed-7e36-4d70-b1e9-b338807b88f1","level":3,"time":"2022-03-14T10:08:20+00:00","remoteAddr":"192.168.1.3","user":"--","app":"core","method":"GET","url":"\/index.php","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Cannot read core\\\/js\\\/core.json\",\"Code\":0,\"Trace\":\"#0 \\\/config\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(83): OC_Template::initTemplateEngine('error')\\n#1 \\\/config\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php(371): OC_Template->__construct('', 'exception', 'error', false)\\n#2 \\\/config\\\/www\\\/owncloud\\\/index.php(76): OC_Template::printExceptionErrorPage(Object(Error))\\n#3 {main}\",\"File\":\"\\\/config\\\/www\\\/owncloud\\\/lib\\\/private\\\/legacy\\\/template.php\",\"Line\":174}"}
`

**Comment by dlandon** [comment]
The webUI update is not recommended for this specific reason.  The second post in the Unraid forum recommends the manual upgrade and gives the steps on how to do that.

I don't know how the webUI update works and cannot give you a recommenadation on how to clean up after that.

Your best bet is to recover from a backup.

**Comment by redxon** [comment]
Holy... Thank you so much! Apparently the update was stuck somewhere in between versions, I did just exactly what was described in the manual update progress and everything works fine again now!

Thank you so much for your fast reply!
