### ISSUE TITLE
Problem whit the las version

### ISSUE THREAD

**Issue by adirgan** [dlandon/owncloud#3]
A php error appears in the last verison when you are trying to access the website

The error is:

This version of ownCloud is not compatible with PHP 7.3
You are currently running PHP 7.3.14-1+ubuntu18.04.1+deb.sury.org+1.

**Comment by dlandon** [comment]
You are using an older version of ownCLoud.  You need to update it.  There is a legacy ownCloud 'owncloud-legacy' docker you can use for the time being.  It is not supported, but can be used to upgrade.
