### ISSUE TITLE
New version of container has OC PHP Version incompatability

### ISSUE THREAD

**Issue by wraythezw** [dlandon/owncloud#6]
This version of ownCloud is not compatible with PHP 7.4
You are currently running PHP 7.4.11.

**Comment by wraythezw** [comment]
root@6fe3aa736992:/# php -v
PHP 7.4.11 (cli) (built: Oct 18 2020 19:39:25) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies

**Comment by dlandon** [comment]
You haven't updated ownCloud to the latest version.  You need to keep ownCloud updated for security reasons.

Change the repository to dlandon/owncloud-legacy and install that version of the docker.  It uses php 7.1 and will run your ownCloud.  Then update ownCloud to the latest version and change the repository back to dlandon/owncloud.  Don't stay on the legacy version, it is not supported.

**Comment by wraythezw** [comment]
Will give it a try - thanks Dlandon

**Comment by wraythezw** [comment]
Dlandon response addressed issue 👍
