### ISSUE TITLE
"This version of ownCloud is not compatible with PHP 7.4"

### ISSUE THREAD

**Issue by Dan-Q** [dlandon/owncloud#7]
After updating to the latest version, all page loads return the error:

> This version of ownCloud is not compatible with PHP 7.4
> You are currently running PHP 7.4.13.

It looks like updating the Dockerfile causes PHP to be updated... but does not trigger an update of ownCloud?

**Comment by dlandon** [comment]
ownCloud cannot be updated automatically.  Use the dlandon/owncloud-legacy docker to get running again and then update ownCloud.
