### ISSUE TITLE
Updating Issues

### ISSUE THREAD

**Issue by TheMrAnderson** [dlandon/owncloud#9]
I'm running this in unRAID but when I try to update, I'm getting some odd behavior.  It was only sometimes failing to load the updater and telling me I have a self-signed cert, which I don't because I use Let's Encrypt and have them automatically updated.  Now it's telling me that every time.  I can't do a manual upgrade because I'm getting an error "Could not open input file: occ" and I'm not finding occ in any of the usual places the ownCloud documentation suggests.  When I did get into the updater to try to update through the UI, it took days to create a checkpoint and the page finally timed out.  Currently my server is in a maintenance mode so nothing is working.

**Comment by dlandon** [comment]
The UI update is not recommended.  As you found out, it has problems. You should probably roll back to the previous version and do the manual update.

**Comment by TheMrAnderson** [comment]
As I said, I can't do a manual upgrade because I'm getting an issue "Could not open input file: occ".  I stumbled across the occ file and get nothing but errors when I execute any command, so at this point it's completely hosed.

**Comment by dlandon** [comment]
Restore a backup.

**Comment by TheMrAnderson** [comment]
And per your ReadMe "Upgrade ownCloud from the webui, Daily branch does not work, so just don't..."  I was using the Stable branch.  You closed this issue when it's not resolved.  I followed your instructions in your documentation and I get this kind of response from you?

**Comment by dlandon** [comment]
The UI update is built into ownCloud and I have absolutely no control over it at all.

**Comment by TheMrAnderson** [comment]
I get you just created the container and don't have control over ownCloud, but I was following your instructions which stated to update via the UI.  If you knew there were issues, as the image maintainer, you should have updated the ReadMe.  It would also be great if you had instructions on how to update using your container because ownCloud's documentatation is useless with your container as every single command in their documentation fails in your container.  If you're going to create a container, you also have to create documentation because as you customize things, you become the only one with the answers.

**Comment by dlandon** [comment]
I don't believe it says to update with the UI.  Read this: https://forums.unraid.net/topic/57801-support-dlandon-owncloud/?tab=comments#comment-566488 for instructions on manually updating.

GitHub is not the place to get support for this docker container on UnRaid.  Use the Unraid Forum.

**Comment by TheMrAnderson** [comment]
Thank you.  I'll keep these instructions for the next upgrade
